# Use the official Redis image as the base image
FROM redis:latest

# Set the working directory inside the container
WORKDIR /app

# Expose the Redis default port
EXPOSE 6379

# Command to start Redis server
CMD ["redis-server"]
